stages:
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

build and run:
  stage: deploy
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - sed -i "s/CI_AWS_REGION/$AWS_REGION/" config.py
    - sed -i "s/CI_SLACK_BOT_TOKEN/$SLACK_BOT_TOKEN/" config.py
    - sed -i "s/CI_SLACK_CHANNEL/$SLACK_CHANNEL/" config.py
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
